### ISSUE TITLE
cryptgeon fails after server restart

### ISSUE THREAD

**Issue by solick** [cupcakearmy/cryptgeon#31] opened 2022-05-23 08:59 UTC
Hi, first thanks for this great piece of code!

I have one problem: Every time, I need to make a server restart, crypteon fails to start successfully.

After running docker-compose up -d again everything works fine.

I have a couple of docker services on that machine, cryptgeon is the only one not starting successfully after server restart.

Any idea on this?

**Comment by cupcakearmy** [comment] 2022-05-23 09:37
maybe memcached not being online when the backend starts? It's the only thing coming to mind.

**Comment by cupcakearmy** [comment] 2022-05-23 09:37
I suppose there was not error message?

**Comment by solick** [comment] 2022-05-23 16:38
> I suppose there was not error message?

The only message was this:
`memcached_1  | Signal handled: Terminated.`

**Comment by cupcakearmy** [comment] 2022-06-07 10:31
I added a small wait script in the container.
Did you have the `depends_on` directive in your docker-compose?

**Comment by solick** [comment] 2022-06-11 17:48
sorry for the late response. Here my complete docker-compose file:

`version: '3.7'

services:
  memcached:
    image: memcached:1.6.15
    entrypoint: memcached -m 128M -I 20M # Limit to 128 MB Ram, 4M per entry, customize at free will.

  app:
    image: cupcakearmy/cryptgeon:1.5.1
    depends_on:
      - memcached
    environment:
      SIZE_LIMIT: 20M
    ports:
      - 9060:5000`

**Comment by cupcakearmy** [comment] 2022-07-16 12:20
Could you try the 2.0 version with redis?

**Comment by solick** [comment] 2022-07-16 18:01
Hi @cupcakearmy I updated and changed to 2.0 and redis. Still it fails after reboot, here the log:

`Attaching to cryptgeon_app_1, cryptgeon_redis_1
redis_1  | 1:C 16 Jul 2022 17:55:38.345 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1  | 1:C 16 Jul 2022 17:55:38.345 # Redis version=7.0.3, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1  | 1:C 16 Jul 2022 17:55:38.345 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1  | 1:M 16 Jul 2022 17:55:38.346 * monotonic clock: POSIX clock_gettime
redis_1  | 1:M 16 Jul 2022 17:55:38.347 * Running mode=standalone, port=6379.
redis_1  | 1:M 16 Jul 2022 17:55:38.347 # Server initialized
redis_1  | 1:M 16 Jul 2022 17:55:38.347 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1  | 1:M 16 Jul 2022 17:55:38.348 * Ready to accept connections
redis_1  | 1:signal-handler (1657994170) Received SIGTERM scheduling shutdown...
redis_1  | 1:M 16 Jul 2022 17:56:10.723 # User requested shutdown...
redis_1  | 1:M 16 Jul 2022 17:56:10.723 * Saving the final RDB snapshot before exiting.
redis_1  | 1:M 16 Jul 2022 17:56:17.716 * DB saved on disk
redis_1  | 1:M 16 Jul 2022 17:56:17.716 # Redis is now ready to exit, bye bye...`

**Comment by cupcakearmy** [comment] 2022-07-17 14:39
Mhhh seems some memory stuff. If both redis and memcache fail to start. Can you check your ram utilisation? Might be that on startup you don't have enough ram to start all the services and OS?

**Comment by cupcakearmy** [comment] 2022-07-21 15:07
Closing this for now. It seems that the redis / memcached containers are failing to boot up due to memory limitations. So it's probably not a cryptgeon issue.
Feel free to reopen if needed :)

**Closed by cupcakearmy** 2022-07-21 15:07 UTC
Labels: question

**Comment by solick** [comment] 2022-08-17 13:12
Sorry for the delay. The machine has 32 GB RAM and as far as I can see no memory problem during startup.

**Comment by cupcakearmy** [comment] 2022-08-17 19:03
No worries :)
But I'm really not sure what the cause might be.

> ```
> redis_1  | 1:signal-handler (1657994170) Received SIGTERM scheduling shutdown...
> ```

Why would redis get a sigterm? I'm a bit confused xD

**Comment by solick** [comment] 2022-08-18 04:50
So I needed to restart my server again and this the logs:

`redis_1  | 1:M 16 Jul 2022 18:02:26.533 * Loading RDB produced by version 7.0.3
redis_1  | 1:M 16 Jul 2022 18:02:26.533 * RDB age 376 seconds
redis_1  | 1:M 16 Jul 2022 18:02:26.533 * RDB memory usage when created 0.82 Mb
redis_1  | 1:M 16 Jul 2022 18:02:26.533 * Done loading RDB, keys loaded: 0, keys expired: 0.
redis_1  | 1:M 16 Jul 2022 18:02:26.533 * DB loaded from disk: 0.011 seconds
redis_1  | 1:M 16 Jul 2022 18:02:26.533 * Ready to accept connections
redis_1  | 1:signal-handler (1660756103) Received SIGTERM scheduling shutdown...
redis_1  | 1:M 17 Aug 2022 17:08:24.033 # User requested shutdown...
redis_1  | 1:M 17 Aug 2022 17:08:24.033 * Saving the final RDB snapshot before exiting.
redis_1  | 1:M 17 Aug 2022 17:08:24.613 * DB saved on disk
redis_1  | 1:M 17 Aug 2022 17:08:24.613 # Redis is now ready to exit, bye bye...
redis_1  | 1:C 17 Aug 2022 17:11:30.981 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1  | 1:C 17 Aug 2022 17:11:30.981 # Redis version=7.0.3, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1  | 1:C 17 Aug 2022 17:11:30.981 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1  | 1:M 17 Aug 2022 17:11:30.982 * monotonic clock: POSIX clock_gettime
redis_1  | 1:M 17 Aug 2022 17:11:30.984 * Running mode=standalone, port=6379.
redis_1  | 1:M 17 Aug 2022 17:11:30.984 # Server initialized
redis_1  | 1:M 17 Aug 2022 17:11:30.984 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1  | 1:M 17 Aug 2022 17:11:30.984 * Loading RDB produced by version 7.0.3
redis_1  | 1:M 17 Aug 2022 17:11:30.984 * RDB age 186 seconds
redis_1  | 1:M 17 Aug 2022 17:11:30.984 * RDB memory usage when created 0.82 Mb
redis_1  | 1:M 17 Aug 2022 17:11:30.984 * Done loading RDB, keys loaded: 0, keys expired: 0.
redis_1  | 1:M 17 Aug 2022 17:11:30.984 * DB loaded from disk: 0.000 seconds
redis_1  | 1:M 17 Aug 2022 17:11:30.984 * Ready to accept connections
redis_1  | 1:signal-handler (1660797721) Received SIGTERM scheduling shutdown...
redis_1  | 1:M 18 Aug 2022 04:42:01.571 # User requested shutdown...
redis_1  | 1:M 18 Aug 2022 04:42:01.628 * Saving the final RDB snapshot before exiting.
redis_1  | 1:M 18 Aug 2022 04:42:06.585 * DB saved on disk
redis_1  | 1:M 18 Aug 2022 04:42:06.683 # Redis is now ready to exit, bye bye...`

it was just a normal server restart...
